import type { Metadata } from 'next';
import PublicHeader from '@/components/layout/PublicHeader';
import { BASE_URL } from '@/lib/structured-data';

export const metadata: Metadata = {
  title: 'Terms of Service | FlashLearn AI',
  description: 'Terms of service for FlashLearn AI. Read our terms and conditions for using the platform.',
  openGraph: {
    title: 'Terms of Service | FlashLearn AI',
    description: 'Terms and conditions for using FlashLearn AI.',
    type: 'website',
    url: `${BASE_URL}/terms`,
  },
  alternates: {
    canonical: `${BASE_URL}/terms`,
  },
};

export default function TermsPage() {
  return (
    <>
      <PublicHeader />
      <main id="main-content" className="min-h-screen bg-gradient-to-br from-gray-50 via-blue-50 to-indigo-50">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-12 sm:py-16">
          <h1 className="text-3xl sm:text-4xl font-bold text-gray-900 mb-2">Terms of Service</h1>
          <p className="text-sm text-gray-500 mb-8">Last updated: March 25, 2026</p>

          <div className="bg-white rounded-xl shadow-sm border border-gray-100 p-6 sm:p-8 prose prose-gray max-w-none">
            <h2>1. Acceptance of Terms</h2>
            <p>
              By accessing or using FlashLearn AI (&quot;the Service&quot;), you agree to be bound by these
              Terms of Service. If you do not agree, do not use the Service. The Service is operated by
              WitUS.Online, a B4C LLC property.
            </p>

            <h2>2. Accounts</h2>
            <p>
              You must provide accurate information when creating an account. You are responsible for
              maintaining the security of your password and account. <strong>You must be at least 13 years old
              to use the Service.</strong> We do not knowingly collect data from children under 13.
              Signup includes an age self-attestation step; selecting &quot;under 13&quot; closes the signup
              flow without saving any information. A privacy-safe version for younger students is in development.
            </p>

            <h2>3. Subscription Plans</h2>
            <ul>
              <li><strong>Free:</strong> 3 AI-generated sets per rolling 30 days, unlimited CSV imports, basic study features</li>
              <li><strong>Monthly Pro ($10/month):</strong> 5 AI-generated sets per rolling 30 days, unlimited CSV imports, all study modes, offline support, priority support</li>
              <li><strong>Annual Pro / Lifetime Learner:</strong> 10 AI-generated sets per rolling 30 days, unlimited CSV imports, all Pro features</li>
            </ul>
            <p className="text-sm">
              AI generation limits apply to text, PDF, YouTube, audio, and image inputs combined. CSV imports do not count against the limit.
              From time to time we may run promotional periods (such as a finals-season boost) that temporarily raise these limits. Promotional caps are
              announced in-app and revert on the published end date.
            </p>
            <p>
              Subscriptions are billed through Stripe. Monthly subscriptions auto-renew unless cancelled.
              You may cancel at any time; access continues until the end of the billing period. Refunds
              are handled on a case-by-case basis.
            </p>

            <h2>4. User Content</h2>
            <p>
              You retain ownership of content you submit (text, files, images). By making flashcard sets
              public, you grant FlashLearn AI a non-exclusive license to display them to other users.
              You may make sets private or delete them at any time.
            </p>
            <p>
              You agree not to submit content that is illegal, harmful, threatening, abusive, defamatory,
              or infringes on intellectual property rights. We reserve the right to remove content that
              violates these terms.
            </p>

            <h2>5. AI-Generated Content</h2>
            <p>
              Flashcards generated by AI are provided &quot;as-is.&quot; While we strive for accuracy,
              AI-generated content may contain errors. You are responsible for reviewing generated
              flashcards for accuracy before using them for study. FlashLearn AI is not liable for
              inaccuracies in AI-generated content.
            </p>

            <h2>6. API Usage</h2>
            <p>
              Use of the FlashLearn AI API is subject to rate limits and usage quotas based on your
              API tier. You may not use the API to build competing services, perform unauthorized
              data scraping, or circumvent rate limits. API keys are confidential; do not share them.
            </p>

            <h2>7. Versus Mode &amp; Challenges</h2>
            <p>
              Versus mode challenges are for educational purposes only. Scores and rankings are
              determined by our composite scoring algorithm. We reserve the right to disqualify
              participants who attempt to manipulate scores or exploit the system.
            </p>

            <h2>8. Teams &amp; Classrooms</h2>
            <p>
              Team administrators and classroom teachers are responsible for managing their members
              and content. Inappropriate behavior by team/classroom members may result in removal
              from the group or account suspension.
            </p>

            <h2>9. Prohibited Conduct</h2>
            <p>You may not:</p>
            <ul>
              <li>Use the Service for any unlawful purpose</li>
              <li>Attempt to gain unauthorized access to accounts or systems</li>
              <li>Upload malicious code, spam, or harmful content</li>
              <li>Circumvent rate limits, security measures, or access controls</li>
              <li>Impersonate others or create misleading accounts</li>
              <li>Use automated tools to access the Service beyond the API</li>
            </ul>

            <h2>10. Account Suspension</h2>
            <p>
              We may suspend or terminate accounts that violate these terms, engage in abuse, or
              pose a security risk. Suspended users will be notified and may appeal through our
              feedback system.
            </p>

            <h2>11. Limitation of Liability</h2>
            <p>
              The Service is provided &quot;as-is&quot; without warranties of any kind. FlashLearn AI,
              WitUS.Online, and B4C LLC shall not be liable for indirect, incidental, special, or
              consequential damages arising from use of the Service.
            </p>

            <h2>12. Changes to Terms</h2>
            <p>
              We may modify these terms at any time. Material changes will be communicated via
              email or in-app notification at least 30 days before taking effect. Continued use
              after changes constitutes acceptance.
            </p>

            <h2>13. Governing Law</h2>
            <p>
              These terms are governed by the laws of the United States. Any disputes shall be
              resolved through binding arbitration.
            </p>

            <h2>14. Contact</h2>
            <p>
              Questions about these terms? Visit our <a href="/contact">contact page</a> or use
              the in-app feedback system.
            </p>

            <p className="text-sm text-gray-500 mt-8">
              FlashLearn AI is a product of WitUS.Online, a B4C LLC property.
            </p>
          </div>
        </div>
      </main>
    </>
  );
}
